#!/bin/bash -x

javac Server.java Client.java

java Server 4444 5555 inventory.txt &
sleep 1
id=$!
cat <<EOF | java Client localhost 4444 5555 & 
setmode T
list
exit
EOF

cat <<EOF | java Client localhost 4444 5555 & 
setmode T
list
exit
EOF

sleep 5

echo "******Expected Output******
phone 20
ps4 17
camera 10
laptop 15
xbox 8
phone 20
ps4 17
camera 10
laptop 15
xbox 8
"

kill $id 




