#!/bin/bash -x

javac Server.java Client.java

java Server 4444 5555 inventory.txt &
sleep 1
id=$!
x=1
i=1
while [ $i -le 10 ]
do
cat <<EOF | java Client localhost 4444 5555 & 
setmode T
purchase cameraman1 camera 1
purchase cameraman1 camera 1
purchase cameraman1 camera 1
cancel $x
exit
EOF
x=$x+1
cat <<EOF | java Client localhost 4444 5555 & 
setmode U
purchase cameraman2 camera 1
purchase cameraman2 camera 1
purchase cameraman2 camera 1
cancel $x
exit
EOF
x=$x+1
i=$(( $i + 1 ))
done	

sleep 10

cat <<EOF | java Client localhost 4444 5555  
list
search cameraman1
search cameraman2
exit
EOF

echo "******Expected End Result******
not crashing

phone 20
ps4 17
camera 0
laptop 15
xbox 8
"

kill $id 




